# Generated by Django 5.0.1 on 2024-01-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='descricao',
            new_name='description',
        ),
    ]
